Prevent zooming
ptr2020/world-of-ptr pull request #59
Opened 2020-08-21 16:27 UTC by filips123

This mostly prevents zooming. Don't merge this, #42 is better.

2020-08-23 20:40 UTC, 1234filip commented
What is it now? You want zooming to be improved or to prevent it? Either way, you should close the stale pull request.

2020-08-23 21:13 UTC, filips123 commented
I want zooming to be improved but @davidmohar said zooming should be prevented but I think @duhecx or someone said that I should make another (this) PR and they will decide which one is better later.

2020-08-24 10:24 UTC, 1234filip commented on world-client/src/features/camera.js
> +    // Prevent native browser zoom because someone said so
Because someone said so? Remove this.

2020-08-24 10:24 UTC, 1234filip requested changes

2020-08-24 10:24 UTC, 1234filip commented on world-client/src/features/camera.js
> +    // Prevent native browser zoom because someone said so
Because someone said so? Remove this.

2020-08-24 10:25 UTC, filiptrplan commented
After Filip fixes the comment, I will merge this into develop. I think giving players the ability to see more of the map than other player is a bad design decision.

2020-08-24 18:18 UTC, 1234filip approved these changes

2020-08-24 18:22 UTC, 1234filip requested changes
You can still zoom in and out by going to the menu in Chrome and clicking the + and - buttons. See if that can be prevented as well.

2020-08-24 18:52 UTC, filips123 commented
I think that can't be prevented.

2020-08-24 19:03 UTC, 1234filip commented
> I think that can't be prevented.

Think != know, research it.

2020-08-27 11:30 UTC, filips123 commented
It seems *something* related to zoom can be detected with `window.devicePixelRatio`. However, those values are different in every browser, maybe also for every device/display. For example:

* Firefox
  * No zoom: 1
  * 110% zoom: 1.0909090909090908
  * 90% zoom: 0.8955223880597015

* Chrome
  * No zoom: 1.100000023841858
  * 110% zoom: 1.2100000381469727
  * 90% zoom: 0.9900000095367432

* Edge
  * No zoom: 1
  * 125% zoom: 1.25
  * 75% zoom: 0.75

But I don't know how to then prevent UI elements from resizing and that visible game area stays the same.

2020-08-27 21:37 UTC, 1234filip approved these changes
Ok seems the window zoom from menu can't be completely prevented. Merging for now so users can't break the game.

2020-08-27 21:38 UTC, merged